# Generated by Django 3.2.2 on 2021-05-13 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='County',
            new_name='Country',
        ),
    ]
